---
# tasks file for /etc/ansible/roles/php
- name: Install Lamp Applications
  become: yes
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'php', 'libapache2-mod-php', 'php-mysql']

- name: Change text
  become: yes
  lineinfile: dest=/etc/apache2/mods-enabled/dir.conf
              regexp='^DirectoryIndex'
              insertbefore=BOF
              line='DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
