name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: jdk
        run: |
            sudo apt update && sudo apt install -y openjdk-17-jdk && echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> ~/.bashrc && echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc && source ~/.bashrc
            java -version
      
      - name: Clone repository
        env:
          SECRET_CLON: ${{ secrets.SECRET_CLON }}
        run: |
          java -version
          git config --global credential.helper store
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git
          cd spring-petclinic
          ./mvnw package
          ls
          

