name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/checkout@v2
        with:
          repository: tms-dos17-onl/spring-petclinic
          token: ${{ secrets.SECRET }}
          fetch-depth: 0
      
      - name: Build  
        run: |
          ls -la
          docker version
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          EOF
          docker run -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven bash -c "mvn clean install && ./mvnw test"
   
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports 

         
