name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        env:
          SECRET_CLON: ${{ secrets.SECRET_CLON }}
        run: |
          git --version
          git config --global credential.helper store # Добавляем это для кэширования учетных данных
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git
          ls

