name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          git --version
          git clone git@github.com:Alex777888777/https://github.com/tms-dos17-onl/spring-petclinic.git
           
     
     
