name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: jdk
        run: apt install openjdk-17-jdk openjdk-17-jre
      
      - name: Clone repository
        env:
          SECRET_CLON: ${{ secrets.SECRET_CLON }}
        run: |
          git --version
          git config --global credential.helper store
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git
          cd spring-petclinic
          ./mvnw package
          ls
          

