name: My_pipeline

on:
  push:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17
      options: --privileged  # Добавляем привилегии для работы с Docker

    steps:
    

    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: tms-dos17-onl/spring-petclinic
        token: ${{ secrets.SECRET_CLON }}
        fetch-depth: 0  # Для получения всех исторических коммитов

    - name: Build with Maven
      run: |
        
        ./mvnw -B package

    # Добавьте другие шаги, связанные с Docker, здесь, если это необходимо


 

          

          

