name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Clone repository
        env:
          SECRET_CLON: ${{ secrets.SECRET_CLON }}
        run: |
          git config --global credential.helper store
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git

      - name: Install latest Docker
        run: |
           sudo apt-get update
           sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
           sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
           sudo apt-get update
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io    
      
      - name: Build
        run: |
          docker version
          docker run hello-world
          sudo chmod -R 777 spring-petclinic
          cd spring-petclinic
          ./mvnw package
        
          

          

