name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          ACCESS_TOKEN: ${{ secrets.SECRET_CLON }} # Используем секрет
        run: |
          git --version
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git
          ls
