name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
          git --version
          git clone https://github.com/spring-projects/spring-petclinic.git
           
     
     
