name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/checkout@v2
        with:
          repository: tms-dos17-onl/spring-petclinic
          token: ${{ secrets.SECRET }}
          fetch-depth: 0
      
      - name: Build Docker 
        run: |
          cd ..
          pwd
          ls
          chmod -R 777 Alex-Krylov
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          WORKDIR /tmp
          # Adjust the path to copy the necessary content
          COPY . /tmp
          RUN ls
          WORKDIR /tmp
          RUN ls -la   # Проверяем, что файл mvnw присутствует
          RUN ./mvnw package && ./mvnw test
          EOF


         
