name: My_pipeline2
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest

    steps:
    
       - name: Use 
         run :  |
          mvn -version
          whoami
          
          java -version
