name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17
    steps:
     
      - name: Clone repository
        env:
          SECRET_CLON: ${{ secrets.SECRET }}
        run: |
          git config --global credential.helper store
          git clone https://${SECRET}@github.com/tms-dos17-onl/spring-petclinic.git
      
      - name: Build Docker 
        run: |
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          EOF
      - name: Run Maven build inside Docker container
        run: |
          ls -la
          docker run -it --rm -v "$(pwd)":/usr/src/mymaven mvn clean install    
          
          WORKDIR /spring-petclinic
          RUN ./mvnw -B package
          EOF
