name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        env:
          NODE_AUTH_TOKEN: ${{ secrets.class }}
        run: |
          git --version
          git clone https://github.com/Alex777888777/spring-petclinic.git
          ls
           
     
     
