name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: |
           mkdir file
           ls
           cd file
           pwd
     
     
