name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker 
        run: |
          docker build --build-arg GITHUB_TOKEN=${{ secrets.SECRET_CLON }} -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          
          ARG GITHUB_TOKEN
          ENV GITHUB_TOKEN=$GITHUB_TOKEN

          RUN git clone https://${GITHUB_TOKEN}@github.com/tms-dos17-onl/spring-petclinic.git
          WORKDIR /spring-petclinic
          RUN ./mvnw -B package
          EOF
        
      - name: Run Maven build inside Docker container
        run: |
          docker run -it --rm maven mvn clean install


