name: My_pipeline

on:
  push:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17
      options: --privileged 

    steps:
    

    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: tms-dos17-onl/spring-petclinic
        token: ${{ secrets.SECRET_CLON }}
        fetch-depth: 0  

    - name: Build with Maven
      run: |
       
        mvn -version
        java -version
        ./mvnw -B package

          

          

