name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/checkout@v2
        with:
          repository: tms-dos17-onl/spring-petclinic
          token: ${{ secrets.SECRET }}
          fetch-depth: 0
      
      - name: Get User Email
        id: email
        run: |
          USER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.SECRET }}" \
          https://api.github.com/user/emails | jq -r '.[0].email')
          echo "User Email: $USER_EMAIL"
      
      - name: Build  
        run: |
          ls -la
          docker version
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          EOF
          docker run -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven bash -c "mvn clean install && ./mvnw test"
   
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports 
          
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          text: 'Результат сборки: ${{ job.status }}'
        env:
        
           SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
 
