name: My_pipeline

on:
  push:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.3-openjdk-17
      options: --privileged 

    steps:
     - name: Clone repository
       env:
          SECRET_CLON: ${{ secrets.SECRET_CLON }}
       run: |
          sudo apt install maven
          
          git config --global credential.helper store
          git clone https://${SECRET_CLON}@github.com/tms-dos17-onl/spring-petclinic.git
      
     - name: Build
       run: |
         
          ls -la
          cd spring-petclinic
          ./mvnw -B package
          

          

