name: My_pipeline2
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
  
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build custom Docker image
      run: docker build -t my-custom-image .

    - name: Use custom Docker image
      run: |
        docker run my-custom-image java -version
        docker run my-custom-image mvn -version
