name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/checkout@v2
        with:
          repository: tms-dos17-onl/spring-petclinic
          token: ${{ secrets.SECRET }}
          fetch-depth: 0
      
      - name: Build Docker 
        run: |
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          WORKDIR /tmp
          COPY . /tmp
          ls /tmp
          RUN pwd && ls
          RUN /tmp/mvnw package && /tmp/mvnw test
          EOF

         
