name: My_pipeline
on:
  push:
    branches:
      - main
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check 
        uses: actions/checkout@v2
        with:
          repository: tms-dos17-onl/spring-petclinic
          token: ${{ secrets.SECRET }}
          fetch-depth: 0
      
      - name: Build Docker 
        run: |
          pwd
          ls -l /usr/src/mymaven
          docker build -t maven - <<EOF
          FROM maven:3.8.4-openjdk-17
          WORKDIR /home/runner/work/Alex-Krylov/Alex-Krylov      
          RUN /home/runner/work/Alex-Krylov/Alex-Krylov/mvnw package && /home/runner/work/Alex-Krylov/Alex-Krylov/mvnw test
          EOF

         
