name: My_pipeline

on:
  push:
    branches:
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    container: 
      image: openjdk:17
      options: --privileged  # Добавляем привилегии для работы с Docker

    services:
      docker:
        image: docker:latest
        options: --privileged  # Привилегии для Docker-in-Docker

    steps:
    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: tms-dos17-onl/spring-petclinic
        token: ${{ secrets.SECRET_CLON }}
        fetch-depth: 0  # Для получения всех исторических коммитов

    - name: Build with Maven
      run: |
        
        docker -version
        ./mvnw -B package

 

          

          

